### PR TITLE
Pagination

### PR DESCRIPTION
**Pull request by ABDALLAHKAJJ**
Pagination problem solved.

### CODE REVIEW

**Review by ABDALLAHKAJJ — COMMENTED** [review]
IN-3: Ana Veri sayfası

**Comment by foaudkajj** [comment]
Vaybe maşaallah
Have you tested the page by changing the master data?
For example, changing from Color to Branches. Is still working after doing that?

**Comment by ABDALLAHKAJJ** [comment]
branches and payment methods have only a few data, I will add some and see what will happen.

**Comment by ABDALLAHKAJJ** [comment]
yup, it's working totally fine.
image

**Comment by foaudkajj** [comment]
Add some dummy data and test it.
You should always do a heavy test after changing any thing.

**Comment by ABDALLAHKAJJ** [comment]
> yup, it's working totally fine.
> image

already done

**Review by foaudkajj — APPROVED** [review]
Good Work

**Pull request merged**
